# required = ["github.com/labstack/echo"]

# [[constraint]]
#   name = "github.com/labstack/echo"
#   version = "3.2.1"

# [[constraint]]
#   name = "github.com/labstack/echo/middleware"

# [[constraint]]
#   name = "upper.io/db.v3"
#   version = "3.3.0"

# [[constraint]]
#   name = "github.com/go-sql-driver"
#   version = "1.3"

[prune]
  go-tests = true
  unused-packages = true
